name: Encode to Base64

on:
  schedule:
    - cron: "0 1 * * *" # 每天凌晨1点运行
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file from private repository
      run: |
        echo "URL: ${{ secrets.PRIVATE_FILE_URL }}" # 输出以供调试
        curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" -o clash.yaml "${{ secrets.PRIVATE_FILE_URL }}"

    - name: Convert file to Base64
      id: encode
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const filePath = './clash.yaml';
          const fileContent = fs.readFileSync(filePath, 'utf8');
          const base64Content = Buffer.from(fileContent).toString('base64');
          console.log("Base64 content encoded"); // 仅输出编码提示，不输出内容

    - name: Save Base64 content to GitHub Secrets
      uses: actions/github-script@v5
      with:
        script: |
          const base64Content = "${{ steps.encode.outputs.result }}";
          await github.actions.createOrUpdateSecretForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            secret_name: 'ENCODED_BASE64',
            encrypted_value: base64Content,
            key_id: 'your_github_repo_public_key_id'
          });
