name: Filter Nodes

on:
  push:
    branches:
      - main

jobs:
  run-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run filter_nodes script
        run: |
          python filter_nodes.py

      - name: Upload filtered nodes
        uses: actions/upload-artifact@v3
        with:
          name: filtered_nodes
          path: filtered_nodes.json

      - name: Push to Gist
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d @- \
            https://api.github.com/gists/b18ae65aef55c646a6e857266aec86f4 <<EOF
            {
              "files": {
                "clash.yaml": {
                  "content": "$(cat filtered_nodes.json)"
                }
              }
            }
          EOF
