name: Sync with Upstream

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
        # 检出 fork 仓库的代码

      - name: Set Git Identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        # 配置 Git 提交者的身份信息

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/wzdnzd/aggregator.git
        # 添加上游仓库作为 remote

      - name: Fetch Upstream
        run: git fetch upstream
        # 从上游仓库拉取最新代码

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
        # 合并上游仓库的更改到主分支，并允许合并无关的历史

      - name: Push Changes
        run: git push origin main
        # 推送合并后的更改到 fork 仓库的主分支
