name: Update and Filter Nodes

on:
  schedule:
    - cron: '0 */3 * * *'  # 每三小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行节点更新和筛选脚本
        run: |
          python scripts/update_and_filter_nodes.py

      - name: 提交更改
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "自动更新筛选后的节点列表"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
